projects:
  app:
    schemPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4500
  prisma:
    schemaPath: src/generated/prisma-client/prisma-schema.js
    extensions:
      prisma: prisma/prisma.yml